# Basic Site Settings
locale           : "zh-CN" # 既然是国内高校，可以把语言环境改为中文
site_theme       : "default" 
title            : "Yongzhou Liu | 刘永洲"
title_separator  : "-" # 注意：这里是网页标题的分隔符，只能填 "-" 或 "|"
description      : &description "安徽大学刘永洲的个人学术主页 | Yongzhou Liu's Academic Portfolio" 
url              : "https://liuyz007.github.io" 
baseurl          : "" 
repository       : "liuyz007/liuyz007.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar           : "profile.png" # 记得把你的照片命名为 profile.png 并上传到 images 文件夹里
  name             : "刘永洲 (Yongzhou Liu)"
  # pronouns       : "she/her"  # 不需要的话，前面加 # 注释掉
  bio              : "控制工程硕士<br>研究方向：计算机视觉、底层视觉、低光图像增强、深度学习"
  location         : "安徽 合肥 (Hefei, China)"
  employer         : "安徽大学 (Anhui University)"
  email            : "13637060646@163.com" 
  
  # Academic websites (只保留你有的，其他的我都帮你注释掉了)
  orcid            : "https://orcid.org/0009-0007-9056-0624"

  # Repositories and software development
  github           : "liuyz007" # 这里改成了你自己的 GitHub 账号

  # Social media (不需要的都注释掉，以免侧边栏出现空图标)
  # bluesky        : "bsky.app"
